apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api-deployment
spec:
  selector:
    matchLabels:
      app:  delivery-api-app
  replicas: 3    
  template:
    metadata:
      labels:
        app:  delivery-api-app
    spec:
      containers:
      - name:  delivery-api-app
        image: #{repository-image}#
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: #{env-name}#
        volumeMounts:
          - name: secrets 
            mountPath: /app/secrets
            readOnly: true
      imagePullSecrets:
        - name: #{acr-secret-name}#  
      volumes:
      - name: secrets
        secret: 
          secretName: #{appsettings-secret-name}#

---
apiVersion: v1
kind: Service
metadata:
  name:  delivery-api-service
spec:
  selector:
    app:  delivery-api-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  name:  delivery-api-ingress
  namespace: #{env-namespace}#
spec:
  tls:
  - hosts:
    - delivery-api.harveynetwork.com
    secretName: delivery-api-ingress-tls
  rules:
    - host: #{host-url}#
      http:
        paths:  
        - backend:
            serviceName:  delivery-api-service
            servicePort: 80
          path: /