# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'
  imageRepository: 'delivery-api-$(Build.SourceBranchName)'

stages:
  - stage: Build
    displayName: Build project and Test

    jobs:
      - job: Build
        displayName: 'Build Project'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: UseDotNet@2
          displayName: 'Install .Net Core 3.1'
          inputs:
            packageType: 'sdk'
            version: '3.1.100'
            installationPath: $(Agent.ToolsDirectory)/dotnet
        - task: NuGetToolInstaller@1
          displayName: 'Install Nuget Tool'  
          inputs: 
            checkLatest: true

        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: restore
            projects: '**/*.csproj'
        - task: DotNetCoreCLI@2
          displayName: Build Projects
          inputs: 
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        - task: DotNetCoreCLI@2
          displayName: 'Run Unit Tests'
          inputs:
            command: test
            projects: '**/*[Tt]ests/*.csproj'
            arguments: --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
