jobs:
- deployment: '${{ parameters.jobName }}'
  displayName: ${{ coalesce(parameters.jobDisplayName, 'Deploy postman apis') }}
  ${{ if parameters.dependsOn }}:
    dependsOn: '${{ parameters.dependsOn }}'
  ${{ if parameters.condition }}:
    condition: '${{ parameters.condition }}'
  pool:
    vmImage: 'ubuntu-latest' #this property is only considered for Azure Hosted pools.
  #workspace:
    #clean: outputs | resources | all # what to clean up before the job runs
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - bash: echo hello
          
        - template: '/DevOps/pipelines/task-postman-api-upload.yml'
          parameters:
            domain: 'management'
            environment: '${{parameters.environment}}'
            authorizationTokenEndpoint: 'https://localhost:5001'
            authorizationClientId: 'clientid'
            authorizationClientSecret: 'seecret'
            authorizationScopes: 'category_management'
            maxRetryCount: 10
            #additionalEnvironmentSettingsJson: "{ 'licenseCheckLineOfBusiness': 'marine', 'productDefinitionPartitionKey': 'industrymachinery', 'partnerId': 'Contoso' }"
            failOnStderr: false
 