jobs:
- deployment: '${{ parameters.jobName }}'
  displayName: ${{ coalesce(parameters.jobDisplayName, 'Deploy Gateway apis') }}
  ${{ if parameters.dependsOn }}:
    dependsOn: '${{ parameters.dependsOn }}'
  ${{ if parameters.condition }}:
    condition: '${{ parameters.condition }}'
  pool:
    vmImage: 'ubuntu-latest' #this property is only considered for Azure Hosted pools.
  environment: ${{ parameters.environment }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          fetchDepth: 1

        - template: '/azure-infrastructure/pipelines/task-terraform.yml'
          parameters:
            environment: '${{ parameters.environment }}'
            terraformFilesDirectory: '${{ parameters.terraformFilesDirectory }}'