jobs:
- deployment: '${{ parameters.jobName }}'
  displayName: ${{ coalesce(parameters.jobDisplayName, 'Deploy postman apis') }}
  ${{ if parameters.dependsOn }}:
    dependsOn: '${{ parameters.dependsOn }}'
  ${{ if parameters.condition }}:
    condition: '${{ parameters.condition }}'
  pool:
    vmImage: 'ubuntu-latest' #this property is only considered for Azure Hosted pools.
  environment: ${{ parameters.environment }}
  strategy:
    runcOnce:
        deploy:
          steps:
          - checkout: self          

        # - template: '/DevOps/pipelines/task-postman-api-upload.yml'
        #   parameters:
        #     domain: 'management'
        #     environment: '${{parameters.environment}}'
        #     authorizationTokenEndpoint: 'https://localhost:5001'
        #     authorizationClientId: 'test-clientid'
        #     authorizationClientSecret: 'test-seecret'
        #     authorizationScopes: 'category_management'
        #     maxRetryCount: 10
        #     additionalEnvironmentSettingsJson: "{}"
        #     failOnStderr: false
 