kubernetes: 
    namespace: "#{Kubernetes-Namespace}#"
runtime:
    environment: "#{ASPNETCORE_ENVIRONMENT}#"
    ring: "#{Ring}#"
    app_insight_key: "#{ApplicationInsights-InstrumentationKey}#"
    stripe_api_key: "#{Stripe-Api-Key}#"
    shards: "#{Shards}#"

key_vault:
    uri: "#{KeyVault_Uri}#"
    client_id: "#{KeyVault_ActiveDirectory_ClientId}#"
    app_key: "#{KeyVault_ActiveDirectory_AppKey}#"
active_directory:
    tenant_id: "#{ActiveDirectory_Tenant_Id}#"



